const PRODUCTS_QUERY = `query checkout($checkoutId: ID! $domainId: ID!) {
  node(id: $checkoutId) {
    ... on CheckoutNode {
      products {
        edges {
          node {
            id
            createdOn
            name
            variantCount
            description
            shortDescription
            insuranceAmount
            quantity
            slug
            unitOfWeight
            unitOfDimensions
            attributes
            ... on ProductNode {
              skus {
                edges {
                  node {
                    id
                    sku
                    width
                    height
                    length
                    unitOfDimensions
                    unitOfWeight
                    salePrice
                    basePrice
                    weight
                    attributes
                    stripeId
                    orderSkus {
                      edges {
                        node {
                          sku {
                            id
                            sku
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            vendor {
              id
              profile(domainId: $domainId) {
                edges {
                  node {
                    id
                    avatar
                    bio
                    label
                    name
                    address1
                    address2
                    city
                    state
                    zipCode
                    country
                    email
                    phoneNumber
                    stripeConnectUserId
                    paypalPayoutEmail
                    domainCommission
                    slug
                  }
                }
              }
            }
            images(orderBy: "orderingPosition") {
              edges {
                node {
                  id
                  image
                }
              }
            }
          }
        }
      }
    }
  }
}`

const COLLECTIONS_QUERY = `query collections($domainId: ID!, $checkoutId: String) {
  node(id: $domainId) {
    ... on DomainNode {
      id
      collections {
        edges {
          node {
            id
            name
            slug
            isAutogenerated
            productCount
            products(checkouts: $checkoutId) {
              edges {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}`

const CHECKOUT_QUERY = `query checkout($id: ID! $domainId: ID!) {
  node(id: $id) {
    ... on CheckoutNode {
      id
      lookAndFeel {
        seo
      }
      promotion {
        id
        label
        stripeCouponCode
        startDatetime
        endDatetime
        discountValue
        discountType
      }
      shippingPreference
      shipFromLocation {
        id
        name
        address1
        address2
        city
        state
        zipCode
        country
        email
        phoneNumber
      }
      domain {
        id
        stripeConnectUserId
        branding {
          logo
        }
        owner {
          id
          profile(domainId: $domainId) {
            edges {
              node {
                id
              }
            }
          }
        }
        freeShippingThreshold
        freeShippingThresholdTarget
        company {
          currency
          name
          address {
            address1
            city
            country
            zipCode
            phoneNumber
            email
          }
        }
        vendors {
          edges {
            node {
              id
              profile(domainId: $domainId) {
                edges {
                  node {
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`

module.exports = {
  PRODUCTS_QUERY,
  COLLECTIONS_QUERY
}
